# This file was generated by the booostrap.sh script from the
# https://github.com/metro-digital/terraform-google-cf-projectcfg repository

# This file can be deleted after initial Terraform import is done.

import {
  to = module.projectcfg.google_service_account.service_accounts["terraform-iac-pipeline"]
  id = "projects/cf-normen-normen-initia-ww/serviceAccounts/terraform-iac-pipeline@cf-normen-normen-initia-ww.iam.gserviceaccount.com"
}

import {
  to = module.tf_state_bucket.google_storage_bucket.bucket
  id = "cf-normen-normen-initia-ww/tf-state-cf-normen-normen-initia-ww"
}

import {
  to = module.projectcfg.google_project_iam_policy.this
  id = "cf-normen-normen-initia-ww"
}
