# This file was generated by the booostrap.sh script from the
# https://github.com/metro-digital/terraform-google-cf-projectcfg repository

locals {
  project_id          = "cf-normen-normen-initia-ww"
  manager_group       = "normen.normen-initial01-playground-manager@metrosystems.net"
  developer_group     = "normen.normen-initial01-playground-developer@metrosystems.net"
  observer_group      = "normen.normen-initial01-playground-observer@metrosystems.net"
  iac_service_account = "terraform-iac-pipeline@cf-normen-normen-initia-ww.iam.gserviceaccount.com"

  # IAM ready strings (with prefix like group, serviceAccount, ...)
  iam_manager_group       = "group:${local.manager_group}"
  iam_developer_group     = "group:${local.developer_group}"
  iam_observer_group      = "group:${local.observer_group}"
  iam_iac_service_account = "serviceAccount:${local.iac_service_account}"
}
