# This file was generated by the booostrap.sh script from the
# https://github.com/metro-digital/terraform-google-cf-projectcfg repository

terraform {
  backend "gcs" {
    bucket = "tf-state-cf-normen-normen-initia-ww"
    prefix = "projectcfg"
    # can't use local here
    impersonate_service_account = "terraform-iac-pipeline@cf-normen-normen-initia-ww.iam.gserviceaccount.com"
  }
}
