# This file was generated by the booostrap.sh script from the
# https://github.com/metro-digital/terraform-google-cf-projectcfg repository

module "projectcfg" {
  source     = "metro-digital/cf-projectcfg/google"
  project_id = local.project_id
  version    = "~> 3.1"

  # The module automatically grants the same permissions to the Manager, Developer and
  # Observer groups as the panel does. There is no need to explicitly configure them.
  # All other bindings in the project's IAM policy can be configured here:
   iam_policy = [
     # Allow manager group to use this project
     # as billing project for BigQuery jobs
     {
       role = "roles/compute.networkAdmin"
       members = [local.iam_manager_group],
     },
     {
       role = "roles/compute.securityAdmin"
       members = [local.iam_manager_group],
     },
     {     
       role = "roles/cloudprofiler.user"
       members = [local.iam_manager_group],
     },
     {
       role = "roles/monitoring.admin"
       members = [local.iam_manager_group],
     },
     {
       role = "roles/logging.admin"
       members = [local.iam_manager_group],
     },
     {
       role = "roles/compute.instanceAdmin.v1"
       members = [local.iam_manager_group],
     },
     {
       role = "roles/serviceusage.serviceUsageAdmin"
       members = [local.iam_manager_group]
     }


  # project_iam_policy_roles = [
  #      "roles/compute.networkAdmin",
  #      "roles/compute.securityAdmin",
  #      "roles/dns.admin",
  #      "roles/iam.roleAdmin",
  #      "roles/iam.securityAdmin",
  #      "roles/iam.serviceAccountAdmin",
  #      "roles/iam.workloadIdentityPoolAdmin",
  #      "roles/serviceusage.serviceUsageAdmin",
  #      "roles/storage.admin",
  #      "roles/storage.objectAdmin",
  #      "roles/vpcaccess.admin"
   ]
  #   # Same for developer group, but only during working days from 07:00 to 18:59
  #   {
  #     role = "roles/bigquery.jobUser"
  #     members = [
  #       local.iam_developer_group,
  #     ]
  #     condition = {
  #       title       = "Working Hours"
  #       description = "Allow during working hours (Monday-Friday, 7:00 to 18:59)"
  #       expression  = <<-EOC
  #         request.time.getHours('Europe/Berlin') >= 7 &&
  #         request.time.getHours('Europe/Berlin') < 19 &&
  #         // Days of the week range from 0 to 6, where 0 == Sunday and 6 == Saturday.
  #         request.time.getDayOfWeek('Europe/Berlin') >= 1 &&
  #         request.time.getDayOfWeek('Europe/Berlin') <= 5
  #       EOC
  #     }
  #   }
  # ]

  service_accounts = {
    "terraform-iac-pipeline" = {
      display_name = "Terraform IaC pipelines"
      description  = "Service account used in IaC pipeline"
      iam_policy = [
        {
          role = "roles/iam.serviceAccountTokenCreator"
          members = [
            # Allow manager group to impersonate IaC service account
            local.iam_manager_group,
            # Allow service account to impersonate itself, useful for pipelines
            local.iam_iac_service_account
          ]
        }
      ]
      project_iam_policy_roles = [
        "roles/compute.networkAdmin",
        "roles/compute.securityAdmin",
        "roles/dns.admin",
        "roles/iam.roleAdmin",
        "roles/iam.securityAdmin",
        "roles/iam.serviceAccountAdmin",
        "roles/iam.workloadIdentityPoolAdmin",
        "roles/serviceusage.serviceUsageAdmin",
        "roles/storage.admin",
        "roles/storage.objectAdmin",
        "roles/vpcaccess.admin"
      ]
      # Allows usage of this service account from a GitHub Action workflow in the following repositories
      github_action_repositories = ["metro-digital-inner-source/customer-infra"]
    }
  }

  # List of VPC regions to configure. By default, no VPC is provisioned. If
  # the region is given like shown below, a default configuration is used. For
  # more information, see the Terraform documentation for the `vpc_regions`
  # input variable.
  # vpc_regions = {
  #   europe-west1 = {}
  # }

  # List of enabled services
  enabled_services = [
    # Bootstrap creates a GCS bucket in the module to hold the Terraform state,
    # see: tf-state-bucket.tf file. Therefore we also ensure the service is
    # enabled.
    "storage.googleapis.com",
  ]
}
